[libraries]
jsoup = "org.jsoup:jsoup:1.15.3"
junit-api = "org.junit.jupiter:junit-jupiter-api:5.9.2"
# Plugin packages
# This way of applying the plugins was needed for the build-related code in buildSrc/src/main/,
# see https://docs.gradle.org/current/samples/sample_convention_plugins.html#things_to_note.
pluginPackages-checkerFramework = "org.checkerframework:checkerframework-gradle-plugin:0.6.23"
pluginPackages-grgit = "org.ajoberstar.grgit:grgit-gradle:5.0.0"
pluginPackages-jetbrains-changelog = "org.jetbrains.intellij.plugins:gradle-changelog-plugin:2.0.0"
pluginPackages-jetbrains-intellij = "org.jetbrains.intellij.plugins:gradle-intellij-plugin:1.13.0"
# @pin because as per https://plugins.jetbrains.com/docs/intellij/using-kotlin.html#kotlin-standard-library:
#      "If a plugin supports multiple platform versions, it must (...) target the lowest bundled stdlib version"
#      which is different in our case (as this is the Kotlin version bundled into IntelliJ 2022.1).
pluginPackages-jetbrains-kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.20"
pluginPackages-spotless = "com.diffplug.spotless:spotless-plugin-gradle:6.15.0"

[plugins]
taskTree = "com.dorongold.task-tree:2.1.1"
versionCatalogUpdate = "nl.littlerobots.version-catalog-update:0.7.0"
versionsFilter = "se.ascp.gradle.gradle-versions-filter:0.1.16"
